apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  dataSourceRef:
    apiGroup: k8s.volare.dev
    kind: VolarePopulator
    name: volare-populator
